syntax = "proto3";

package proto;

import "proto/trip.proto";

option go_package = "github.com/ThalaPravin/RideMesh/proto;pb";

service MatchingService {
  rpc UpdateLocation(UpdateLocationRequest) returns (UpdateLocationResponse);
  rpc GetNearbyDrivers(GetNearbyDriversRequest) returns (GetNearbyDriversResponse);
}

message UpdateLocationRequest {
  string driver_id = 1;
  Location location = 2;
}

message UpdateLocationResponse {
  bool success = 1;
}

message GetNearbyDriversRequest {
  Location location = 1;
  double radius_km = 2;
  string vehicle_type = 3;
}

message GetNearbyDriversResponse {
  repeated string driver_ids = 1;
}
